// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {time} from '../models';

export function ApproveHost(arg1:model.HostTrustPrompt):Promise<void>;

export function Bootstrap():Promise<model.BootstrapPayload>;

export function BackupSiteLibrary():Promise<string>;

export function CancelTransfer(arg1:string):Promise<Array<model.TransferItem>>;

export function CheckForUpdates():Promise<model.UpdateCheckResult>;

export function ClearAllTransfers():Promise<Array<model.TransferItem>>;

export function ClearBackgroundConnections():Promise<number>;

export function ClearCompletedTransfers():Promise<Array<model.TransferItem>>;

export function ClearLogs():Promise<Array<model.LogItem>>;

export function CloseIdleHiddenConnections(arg1:time.Duration):Promise<number>;

export function CloseSSHSession(arg1:string):Promise<void>;

export function CloseTab(arg1:string):Promise<Array<model.Tab>>;

export function Connect(arg1:string):Promise<Array<model.Tab>>;

export function ConnectionCounts():Promise<number|number>;

export function CreateDirectory(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateLocalTerminalTab(arg1:string):Promise<Array<model.Tab>>;

export function CreateSSHTab(arg1:model.Site):Promise<Array<model.Tab>>;

export function CreateSiteFolder(arg1:string):Promise<model.Config>;

export function CreateTab(arg1:model.Site):Promise<Array<model.Tab>>;

export function CreateTelnetTab(arg1:model.Site):Promise<Array<model.Tab>>;

export function DeleteEntries(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function DeleteEntry(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteSite(arg1:string):Promise<Array<model.Site>>;

export function DeleteSiteFolder(arg1:string):Promise<model.SiteLibraryMutationResult>;

export function Disconnect(arg1:string):Promise<Array<model.Tab>>;

export function DownloadDroppedPaths(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function CompareDirectories(arg1:string,arg2:string,arg3:string):Promise<Array<model.FileComparison>>;

export function SyncDirectories(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExecuteLocalPath(arg1:string):Promise<void>;

export function ExecuteSSHCommand(arg1:model.Site,arg2:string,arg3:number):Promise<Record<string, any>>;

export function ExportRestAPIDocsMarkdown():Promise<string>;

export function GetConfig():Promise<model.Config>;

export function GetLogs():Promise<Array<model.LogItem>>;

export function GetSiteDataDirectory():Promise<string>;

export function GetRESTServerBaseURL():Promise<string>;

export function GetRESTServerPort():Promise<number>;

export function GetRESTServerStatus():Promise<model.RESTServerStatus>;


export function GetRestAPIDocsMarkdown():Promise<string>;

export function GetMCPContractMarkdown(arg1:string):Promise<string>;

export function GetMCPStdioExecutable():Promise<string>;

export function ExportMCPContractMarkdown(arg1:string):Promise<string>;

export function GetSSHOutputBuffer(arg1:string):Promise<string>;

export function GetSites():Promise<Array<model.Site>>;

export function GetTabs():Promise<Array<model.Tab>>;

export function GetTransfers():Promise<Array<model.TransferItem>>;

export function ListLocal(arg1:string,arg2:string):Promise<Array<model.FileEntry>>;

export function ListRemote(arg1:string,arg2:string):Promise<Array<model.FileEntry>>;

export function ListSystemFonts():Promise<Array<string>>;

export function MoveEntriesToDirectory(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function OpenLocalPath(arg1:string):Promise<void>;

export function OpenSiteDataDirectory():Promise<void>;

export function RegisterBackgroundService(arg1:number):Promise<void>;

export function ReloadConfig():Promise<model.Config>;

export function ReloadRuntimeConfig():Promise<model.Config>;

export function RenameEntry(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RenameSiteFolder(arg1:string,arg2:string):Promise<model.SiteLibraryMutationResult>;

export function ReorderSiteFolders(arg1:Array<string>):Promise<model.Config>;

export function ReorderSites(arg1:Array<string>):Promise<Array<model.Site>>;

export function ReorderTabs(arg1:Array<string>):Promise<Array<model.Tab>>;

export function ResetWindowToDefaultScale():Promise<void>;

export function ResizeSSHSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestoreSiteLibraryBackup():Promise<model.SiteLibraryMutationResult|null>;

export function SaveConfig(arg1:model.Config):Promise<model.Config>;

export function SaveSite(arg1:model.Site):Promise<Array<model.Site>>;

export function SelectDirectory():Promise<string>;

export function SelectPPKFile():Promise<string>;

export function ServiceShutdown():Promise<void>;

export function ServiceStartup():Promise<void>;

export function SortSiteFolders():Promise<model.Config>;

export function SortSitesByName():Promise<Array<model.Site>>;

export function StartSSHSession(arg1:model.Site):Promise<string>;

export function StartUpdate(arg1:string):Promise<model.UpdateActionResult>;

export function StartTelnetSession(arg1:model.Site):Promise<string>;

export function StatRemoteEntry(arg1:string,arg2:string):Promise<Record<string, any>>;

export function TogglePauseAllTransfers():Promise<Array<model.TransferItem>>;

export function TogglePauseTransfer(arg1:string):Promise<Array<model.TransferItem>>;

export function UnregisterBackgroundService():Promise<void>;

export function UpdateTabPaths(arg1:string,arg2:string,arg3:string):Promise<Array<model.Tab>>;

export function UploadDroppedPaths(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function UploadDroppedPathsToSite(arg1:model.Site,arg2:Array<string>,arg3:string):Promise<void>;

export function WriteSSHInput(arg1:string,arg2:string):Promise<void>;
