// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveHost(arg1) {
  return window['go']['app']['App']['ApproveHost'](arg1);
}

export function Bootstrap() {
  return window['go']['app']['App']['Bootstrap']();
}

export function BackupSiteLibrary() {
  return window['go']['app']['App']['BackupSiteLibrary']();
}

export function CancelTransfer(arg1) {
  return window['go']['app']['App']['CancelTransfer'](arg1);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function ClearAllTransfers() {
  return window['go']['app']['App']['ClearAllTransfers']();
}

export function ClearBackgroundConnections() {
  return window['go']['app']['App']['ClearBackgroundConnections']();
}

export function ClearCompletedTransfers() {
  return window['go']['app']['App']['ClearCompletedTransfers']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function CloseIdleHiddenConnections(arg1) {
  return window['go']['app']['App']['CloseIdleHiddenConnections'](arg1);
}

export function CloseSSHSession(arg1) {
  return window['go']['app']['App']['CloseSSHSession'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['app']['App']['CloseTab'](arg1);
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function ConnectionCounts() {
  return window['go']['app']['App']['ConnectionCounts']();
}

export function CreateDirectory(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateDirectory'](arg1, arg2, arg3, arg4);
}

export function CreateLocalTerminalTab(arg1) {
  return window['go']['app']['App']['CreateLocalTerminalTab'](arg1);
}

export function CreateSSHTab(arg1) {
  return window['go']['app']['App']['CreateSSHTab'](arg1);
}

export function CreateSiteFolder(arg1) {
  return window['go']['app']['App']['CreateSiteFolder'](arg1);
}

export function CreateTab(arg1) {
  return window['go']['app']['App']['CreateTab'](arg1);
}

export function CreateTelnetTab(arg1) {
  return window['go']['app']['App']['CreateTelnetTab'](arg1);
}

export function DeleteEntries(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteEntries'](arg1, arg2, arg3);
}

export function DeleteEntry(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteEntry'](arg1, arg2, arg3);
}

export function DeleteSite(arg1) {
  return window['go']['app']['App']['DeleteSite'](arg1);
}

export function DeleteSiteFolder(arg1) {
  return window['go']['app']['App']['DeleteSiteFolder'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['app']['App']['Disconnect'](arg1);
}

export function DownloadDroppedPaths(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadDroppedPaths'](arg1, arg2, arg3);
}

export function CompareDirectories(arg1, arg2, arg3) {
  return window['go']['app']['App']['CompareDirectories'](arg1, arg2, arg3);
}

export function SyncDirectories(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SyncDirectories'](arg1, arg2, arg3, arg4);
}

export function ExecuteLocalPath(arg1) {
  return window['go']['app']['App']['ExecuteLocalPath'](arg1);
}

export function ExecuteSSHCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteSSHCommand'](arg1, arg2, arg3);
}

export function ExportRestAPIDocsMarkdown() {
  return window['go']['app']['App']['ExportRestAPIDocsMarkdown']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetSiteDataDirectory() {
  return window['go']['app']['App']['GetSiteDataDirectory']();
}

export function GetRESTServerBaseURL() {
  return window['go']['app']['App']['GetRESTServerBaseURL']();
}

export function GetRESTServerPort() {
  return window['go']['app']['App']['GetRESTServerPort']();
}

export function GetRESTServerStatus() {
  return window['go']['app']['App']['GetRESTServerStatus']();
}

export function GetRestAPIDocsMarkdown() {
  return window['go']['app']['App']['GetRestAPIDocsMarkdown']();
}

export function GetMCPContractMarkdown(arg1) {
  return window['go']['app']['App']['GetMCPContractMarkdown'](arg1);
}

export function ExportMCPContractMarkdown(arg1) {
  return window['go']['app']['App']['ExportMCPContractMarkdown'](arg1);
}

export function GetSSHOutputBuffer(arg1) {
  return window['go']['app']['App']['GetSSHOutputBuffer'](arg1);
}

export function GetSites() {
  return window['go']['app']['App']['GetSites']();
}

export function GetTabs() {
  return window['go']['app']['App']['GetTabs']();
}

export function GetTransfers() {
  return window['go']['app']['App']['GetTransfers']();
}

export function ListLocal(arg1, arg2) {
  return window['go']['app']['App']['ListLocal'](arg1, arg2);
}

export function ListRemote(arg1, arg2) {
  return window['go']['app']['App']['ListRemote'](arg1, arg2);
}

export function ListSystemFonts() {
  return window['go']['app']['App']['ListSystemFonts']();
}

export function MoveEntriesToDirectory(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['MoveEntriesToDirectory'](arg1, arg2, arg3, arg4);
}

export function OpenLocalPath(arg1) {
  return window['go']['app']['App']['OpenLocalPath'](arg1);
}

export function OpenSiteDataDirectory() {
  return window['go']['app']['App']['OpenSiteDataDirectory']();
}

export function RegisterBackgroundService(arg1) {
  return window['go']['app']['App']['RegisterBackgroundService'](arg1);
}

export function ReloadConfig() {
  return window['go']['app']['App']['ReloadConfig']();
}

export function ReloadRuntimeConfig() {
  return window['go']['app']['App']['ReloadRuntimeConfig']();
}

export function RenameEntry(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameEntry'](arg1, arg2, arg3, arg4);
}

export function RenameSiteFolder(arg1, arg2) {
  return window['go']['app']['App']['RenameSiteFolder'](arg1, arg2);
}

export function ReorderSiteFolders(arg1) {
  return window['go']['app']['App']['ReorderSiteFolders'](arg1);
}

export function ReorderSites(arg1) {
  return window['go']['app']['App']['ReorderSites'](arg1);
}

export function ReorderTabs(arg1) {
  return window['go']['app']['App']['ReorderTabs'](arg1);
}

export function ResetWindowToDefaultScale() {
  return window['go']['app']['App']['ResetWindowToDefaultScale']();
}

export function ResizeSSHSession(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResizeSSHSession'](arg1, arg2, arg3);
}

export function RestoreSiteLibraryBackup() {
  return window['go']['app']['App']['RestoreSiteLibraryBackup']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveSite(arg1) {
  return window['go']['app']['App']['SaveSite'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectPPKFile() {
  return window['go']['app']['App']['SelectPPKFile']();
}

export function ServiceShutdown() {
  return window['go']['app']['App']['ServiceShutdown']();
}

export function ServiceStartup() {
  return window['go']['app']['App']['ServiceStartup']();
}

export function SortSiteFolders() {
  return window['go']['app']['App']['SortSiteFolders']();
}

export function SortSitesByName() {
  return window['go']['app']['App']['SortSitesByName']();
}

export function StartSSHSession(arg1) {
  return window['go']['app']['App']['StartSSHSession'](arg1);
}

export function StartUpdate(arg1) {
  return window['go']['app']['App']['StartUpdate'](arg1);
}

export function StartTelnetSession(arg1) {
  return window['go']['app']['App']['StartTelnetSession'](arg1);
}

export function StatRemoteEntry(arg1, arg2) {
  return window['go']['app']['App']['StatRemoteEntry'](arg1, arg2);
}

export function TogglePauseAllTransfers() {
  return window['go']['app']['App']['TogglePauseAllTransfers']();
}

export function TogglePauseTransfer(arg1) {
  return window['go']['app']['App']['TogglePauseTransfer'](arg1);
}

export function UnregisterBackgroundService() {
  return window['go']['app']['App']['UnregisterBackgroundService']();
}

export function UpdateTabPaths(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateTabPaths'](arg1, arg2, arg3);
}

export function UploadDroppedPaths(arg1, arg2, arg3) {
  return window['go']['app']['App']['UploadDroppedPaths'](arg1, arg2, arg3);
}

export function UploadDroppedPathsToSite(arg1, arg2, arg3) {
  return window['go']['app']['App']['UploadDroppedPathsToSite'](arg1, arg2, arg3);
}

export function WriteSSHInput(arg1, arg2) {
  return window['go']['app']['App']['WriteSSHInput'](arg1, arg2);
}
